apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "resize-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "resize-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "resize-operator.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "resize-operator.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "resize-operator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: manager
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /manager
          args:
            {{- if .Values.args.leaderElect }}
            - --leader-elect
            {{- end }}
            - --health-probe-bind-address={{ .Values.args.bindAddress }}
            - --metrics-bind-address={{ .Values.args.metricsBindAddress }}
            {{- if .Values.args.timeZone }}
            - --time-zone={{ .Values.args.timeZone }}
            {{- end }}
            {{- if .Values.args.kubeApiQps }}
            - --kube-api-qps={{ .Values.args.kubeApiQps }}
            {{- end }}
            {{- if .Values.args.kubeApiBurst }}
            - --kube-api-burst={{ .Values.args.kubeApiBurst }}
            {{- end }}
            {{- if .Values.args.metricsTimeout }}
            - --metrics-timeout={{ .Values.args.metricsTimeout }}
            {{- end }}
            {{- if .Values.args.resizeTimeout }}
            - --resize-timeout={{ .Values.args.resizeTimeout }}
            {{- end }}
            {{- if .Values.args.patchTimeout }}
            - --patch-timeout={{ .Values.args.patchTimeout }}
            {{- end }}
            {{- with .Values.args.extra }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          ports:
            - name: metrics
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
