{{- if .Values.policy.create -}}
apiVersion: resize.maxim.technology/v1alpha1
kind: InPlacePodResize
metadata:
  name: {{ .Values.policy.name }}
  labels:
    {{- include "resize-operator.labels" . | nindent 4 }}
spec:
  {{- toYaml .Values.policy.spec | nindent 2 }}
{{- end -}}
