//go:build !ignore_autogenerated

/*
Copyright 2026 Dmitry Ponomaryov

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlgorithmSpec) DeepCopyInto(out *AlgorithmSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlgorithmSpec.
func (in *AlgorithmSpec) DeepCopy() *AlgorithmSpec {
	if in == nil {
		return nil
	}
	out := new(AlgorithmSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BoundsSpec) DeepCopyInto(out *BoundsSpec) {
	*out = *in
	if in.CPUMin != nil {
		in, out := &in.CPUMin, &out.CPUMin
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.CPUMax != nil {
		in, out := &in.CPUMax, &out.CPUMax
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.MemoryMin != nil {
		in, out := &in.MemoryMin, &out.MemoryMin
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.MemoryMax != nil {
		in, out := &in.MemoryMax, &out.MemoryMax
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.MinChangeCPU != nil {
		in, out := &in.MinChangeCPU, &out.MinChangeCPU
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.MinChangeMemory != nil {
		in, out := &in.MinChangeMemory, &out.MinChangeMemory
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BoundsSpec.
func (in *BoundsSpec) DeepCopy() *BoundsSpec {
	if in == nil {
		return nil
	}
	out := new(BoundsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InPlacePodResize) DeepCopyInto(out *InPlacePodResize) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InPlacePodResize.
func (in *InPlacePodResize) DeepCopy() *InPlacePodResize {
	if in == nil {
		return nil
	}
	out := new(InPlacePodResize)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InPlacePodResize) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InPlacePodResizeList) DeepCopyInto(out *InPlacePodResizeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InPlacePodResize, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InPlacePodResizeList.
func (in *InPlacePodResizeList) DeepCopy() *InPlacePodResizeList {
	if in == nil {
		return nil
	}
	out := new(InPlacePodResizeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InPlacePodResizeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InPlacePodResizeSpec) DeepCopyInto(out *InPlacePodResizeSpec) {
	*out = *in
	in.NamespaceSelector.DeepCopyInto(&out.NamespaceSelector)
	if in.PodSelector != nil {
		in, out := &in.PodSelector, &out.PodSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	out.Resources = in.Resources
	out.Algorithm = in.Algorithm
	in.Bounds.DeepCopyInto(&out.Bounds)
	out.Thresholds = in.Thresholds
	in.Timing.DeepCopyInto(&out.Timing)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InPlacePodResizeSpec.
func (in *InPlacePodResizeSpec) DeepCopy() *InPlacePodResizeSpec {
	if in == nil {
		return nil
	}
	out := new(InPlacePodResizeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InPlacePodResizeStatus) DeepCopyInto(out *InPlacePodResizeStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastRunTime != nil {
		in, out := &in.LastRunTime, &out.LastRunTime
		*out = (*in).DeepCopy()
	}
	if in.LastCapabilityCheckTime != nil {
		in, out := &in.LastCapabilityCheckTime, &out.LastCapabilityCheckTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InPlacePodResizeStatus.
func (in *InPlacePodResizeStatus) DeepCopy() *InPlacePodResizeStatus {
	if in == nil {
		return nil
	}
	out := new(InPlacePodResizeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedResourcesSpec) DeepCopyInto(out *ManagedResourcesSpec) {
	*out = *in
	out.Requests = in.Requests
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedResourcesSpec.
func (in *ManagedResourcesSpec) DeepCopy() *ManagedResourcesSpec {
	if in == nil {
		return nil
	}
	out := new(ManagedResourcesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceSelector) DeepCopyInto(out *NamespaceSelector) {
	*out = *in
	if in.Include != nil {
		in, out := &in.Include, &out.Include
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Exclude != nil {
		in, out := &in.Exclude, &out.Exclude
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceSelector.
func (in *NamespaceSelector) DeepCopy() *NamespaceSelector {
	if in == nil {
		return nil
	}
	out := new(NamespaceSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceToggles) DeepCopyInto(out *ResourceToggles) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceToggles.
func (in *ResourceToggles) DeepCopy() *ResourceToggles {
	if in == nil {
		return nil
	}
	out := new(ResourceToggles)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThresholdsSpec) DeepCopyInto(out *ThresholdsSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThresholdsSpec.
func (in *ThresholdsSpec) DeepCopy() *ThresholdsSpec {
	if in == nil {
		return nil
	}
	out := new(ThresholdsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimingSpec) DeepCopyInto(out *TimingSpec) {
	*out = *in
	out.Interval = in.Interval
	out.Cooldown = in.Cooldown
	out.StabilizationWindow = in.StabilizationWindow
	if in.MaxTotalCPUIncrease != nil {
		in, out := &in.MaxTotalCPUIncrease, &out.MaxTotalCPUIncrease
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.MaxTotalMemoryIncrease != nil {
		in, out := &in.MaxTotalMemoryIncrease, &out.MaxTotalMemoryIncrease
		x := (*in).DeepCopy()
		*out = &x
	}
	out.CapabilityCheckInterval = in.CapabilityCheckInterval
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimingSpec.
func (in *TimingSpec) DeepCopy() *TimingSpec {
	if in == nil {
		return nil
	}
	out := new(TimingSpec)
	in.DeepCopyInto(out)
	return out
}
